version: '3'

services:
  auer-node-app:
    build: .
    image: auer-node-app
    environment:
      - MONGODB_URL=mongodb://auer-mongodb:27017/node-boilerplate
    ports:
      - '22111:3000'
    depends_on:
      - auer-mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - auer-node-network

  auer-mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '22112:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - auer-node-network

volumes:
  dbdata:

networks:
  auer-node-network:
    driver: bridge
